version: '2'
networks:
  default:
    external:
      name: alpinenjs_bridge

services:
  mongodb:
    image: mongo:4.0.4
    volumes:
      - './data:/data/alpine'
    restart: always
  app:
    build: ./
    image: 7677/alpineplatform
    ports:
      - "4000:4000"
    restart: always
    links:
      - mongodb
      